In [1]:
import numpy as np

In [9]:
ar = np.array([
               [1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [1,12,4,15,19]
               ])


print(ar)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1 12  4 15 19]]


In [10]:
ar[2:,3:]

array([[14, 15],
       [19, 20],
       [15, 19]])

In [14]:
ar[0:5,2:3] = 1

ar

array([[ 1,  2,  1,  4,  5],
       [ 6,  7,  1,  9, 10],
       [11, 12,  1, 14, 15],
       [16, 17,  1, 19, 20],
       [ 1, 12,  1, 15, 19]])

In [15]:
ar2 = np.array([
    [1,12,5,15],
    [3,4,5,6],
    [7,8,9,10],
    [11,12,13,14]
    ])

In [19]:
np.fill_diagonal(ar2,0)

ar2

array([[ 0, 12,  5, 15],
       [ 3,  0,  5,  6],
       [ 7,  8,  0, 10],
       [11, 12, 13,  0]])

In [22]:
arr = np.arange(36).reshape(6,6)

arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [23]:
arr[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [21]:
arr2 = np.arange(25).reshape(5,5)

print(arr2,"\n\n")
print(arr2[0:1,0:],"\n") # Top Border
print(arr2[1:,0:1],"\n") # Left Border
print(arr2[4:5,1:],"\n") # Bottom border
print(arr2[1:4,4:5],"\n") # Right border



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 


[[0 1 2 3 4]] 

[[ 5]
 [10]
 [15]
 [20]] 

[[21 22 23 24]] 

[[ 9]
 [14]
 [19]] 



In [23]:
arr3 = np.arange(12).reshape(3,4)

print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
arr4 = np.arange(12).reshape(3,4)
arr5 = np.arange(12).reshape(3,4)

print(arr4 + arr5)

# print(arr4)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [11]:
arr6 = np.arange(16).reshape(4,4)
print(arr6,"\n")

print(arr6[0:1,0:] + arr6[3:4,0:],"\n")
print(arr6[0:,0:1] + arr6[0:,3:4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[12 14 16 18]] 

[[ 3]
 [11]
 [19]
 [27]]


In [5]:
arr = np.arange(25).reshape(5,5)

# print(arr)


print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


12.0
12.0
7.211102550927978
52.0


In [8]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

mean_val = np.mean(arr)
std_val = np.std(arr)

# Step 3: Normalize
normalized_arr = (arr - mean_val) / std_val

print(normalized_arr)
print(np.mean(normalized_arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0


In [14]:
arr = np.arange(1,10).reshape(3,3)
ar1 = np.arange(1,4).reshape(3,1)


arr = arr[0:] - ar1[0:3,0]
print(arr)
# for idx in arr.shape[0]:
#     arr[0] + ar1

[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [5]:
arr = np.arange(1,10).reshape(3,3)

print(arr)

arr = arr.reshape(1,9)
print(arr)

arr = arr.reshape(9,1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [7]:
arr = np.arange(1,26).reshape(5,5)

print(arr)

arr = arr.reshape(1,25)

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]]


In [6]:
person_dtype = np.dtype([
    ('name', 'U20'),   # string of up to 20 characters
    ('age', 'i4'),     # 32-bit integer
    ('weight', 'f4')   # 32-bit float
])

arr = np.array([

    ('Gopal',23,66.30),
    ('Krishna',27,42.34),
    ('Ram',21,77.35)

],dtype=person_dtype)


# print(arr)

sorted_people = np.sort(arr, order = 'age')

print(sorted_people)

[('Ram', 21, 77.35) ('Gopal', 23, 66.3 ) ('Krishna', 27, 42.34)]


In [13]:
random_arr = np.random.randint(0,20,size=(4,4))

# print(random_arr)

random_arr[random_arr > 10] = 10

print(random_arr)

[[10 10 10  5]
 [ 6  7  4  1]
 [ 4  7 10 10]
 [10 10  0 10]]
