In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

print(arr1)
print(arr1.shape)

arr1.reshape(5,1)
print(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)
[1 2 3 4 5]
(5,)


In [19]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# print(arr)

# print(arr[1:3,2:4])
print(arr[0:3][0:1])

[[1 2 3 4]]


In [13]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])