In [1]:
import numpy as np

In [9]:
ar = np.array([
               [1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [1,12,4,15,19]
               ])


print(ar)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1 12  4 15 19]]


In [10]:
ar[2:,3:]

array([[14, 15],
       [19, 20],
       [15, 19]])

In [14]:
ar[0:5,2:3] = 1

ar

array([[ 1,  2,  1,  4,  5],
       [ 6,  7,  1,  9, 10],
       [11, 12,  1, 14, 15],
       [16, 17,  1, 19, 20],
       [ 1, 12,  1, 15, 19]])

In [15]:
ar2 = np.array([
    [1,12,5,15],
    [3,4,5,6],
    [7,8,9,10],
    [11,12,13,14]
    ])

In [19]:
np.fill_diagonal(ar2,0)

ar2

array([[ 0, 12,  5, 15],
       [ 3,  0,  5,  6],
       [ 7,  8,  0, 10],
       [11, 12, 13,  0]])

In [22]:
arr = np.arange(36).reshape(6,6)

arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [23]:
arr[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [21]:
arr2 = np.arange(25).reshape(5,5)

print(arr2,"\n\n")
print(arr2[0:1,0:],"\n") # Top Border
print(arr2[1:,0:1],"\n") # Left Border
print(arr2[4:5,1:],"\n") # Bottom border
print(arr2[1:4,4:5],"\n") # Right border



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 


[[0 1 2 3 4]] 

[[ 5]
 [10]
 [15]
 [20]] 

[[21 22 23 24]] 

[[ 9]
 [14]
 [19]] 



In [23]:
arr3 = np.arange(12).reshape(3,4)

print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
